# Basic dependabot.yml file with
# minimum configuration for npm package manager

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
		open-pull-requests-limit: 10
    schedule:
      interval: "daily"
